### ISSUE TITLE
The NuGet package is missing

### ISSUE THREAD

**Issue by grantbowering** [IntelliTect/AspNetCore.TestHost.WindowsAuth#8]
The NuGet [link off the readme](https://www.nuget.org/packages/IntelliTect.AspNetCore.TestHost.WindowsAuth) 404s.
Browsing NuGet doesn't turn up any plausible matches.
What happened to this?  :(

**Comment by ascott18** [comment]
Looks like the work was done to setup the build, but the publish was never kicked off. @adamskt - any ideas?

**Comment by ascott18** [comment]
@adamskt - I pushed to the `release` branch, which is the condition on the nuget push task, but had to manually trigger a build because it only triggers on `master` and `release/*`. Then, the nuget push failed because it looks like the Nuget credentials have expired and I can't figure out where Pipelines is even pulling them from.

**Comment by adamskt** [comment]
Pushed package to NuGet and fixed in f717047
